// CommonJS, every file is module (by default)
// Modules - Encapsulated Code (only share minimum)
const names = require('./04-names.js')
const sayHi = require('./05-utilities')
const data = require('./06-alt-sabor')
require('./07-mind-grenade.js')
sayHi('Code the Dream')
sayHi(names.ann)
sayHi(names.jeff)